---
dependencies:
  - role: user
    user_info:
    - name: automator
      type: restricted
      sudoers_template: '99-automator-analytics.j2'
      authorized_keys: "{{ AS_AUTOMATOR_AUTHORIZED_KEYS }}"
    user_rbash_links:
      - /usr/bin/sudo
      - /usr/bin/scp
    when: AS_AUTOMATOR_AUTHORIZED_KEYS|length != 0
