---
- name: ora | restart ora
  supervisorctl_local: >
    name=ora
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=restarted
  when: ora_installed is defined and not devstack

- name: ora | restart ora_celery
  supervisorctl_local: >
    name=ora_celery
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=restarted
  when: ora_installed is defined and not devstack
