# Creates a single user on a server
# By default no super-user privileges
# Example: ansible-playbook -i "jarv.m.sandbox.edx.org,"  ./create_user.yml -e "user=jarv"
# Create a user with sudo privileges
# Example: ansible-playbook -i "jarv.m.sandbox.edx.org,"  ./create_user.yml -e "user=jarv" -e "give_sudo=true"
- name: Create a single user
  hosts: all
  sudo: True
  gather_facts: False
  pre_tasks:
    - fail: msg="You must pass a user into this play"
      when: user is not defined
    - name: give access with no sudo
      set_fact:
        user_info:
          - name: "{{ user }}"
            github: true
      when: give_sudo is not defined
    - name: give access with sudo
      set_fact:
        user_info:
          - name: "{{ user }}"
            type: admin
            github: true
      when: give_sudo is defined
  roles:
    - user
