---
dependencies:
  - supervisor
  - role: rbenv
    rbenv_user: "{{ edxapp_user }}"
    rbenv_dir: "{{ edxapp_app_dir }}"
    rbenv_ruby_version: "{{ edxapp_ruby_version }}"
  - devpi
  - role: user
    user_info:
      - name: automator
        type: restricted
        sudoers_template: '99-edxapp-manage-cmds.j2'
        authorized_keys: "{{ EDXAPP_AUTOMATOR_AUTHORIZED_KEYS }}"
    when: EDXAPP_AUTOMATOR_AUTHORIZED_KEYS|length != 0
