# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---
# Check out xqueue repo to {{xqueue_code_dir}}
#
#

- name: xqueue | create application user
  user: >
    name="{{ xqueue_user }}"
    home="{{ xqueue_app_dir }}"
    createhome=no
    shell=/bin/false
  notify:
    - xqueue | restart xqueue

- name: xqueue | create xqueue app and venv dir
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ xqueue_user }}"
    group="{{ common_web_group }}"
  notify:
    - xqueue | restart xqueue
  with_items:
    - "{{ xqueue_app_dir }}"
    - "{{ xqueue_venvs_dir }}"

- name: xqueue | install a bunch of system packages on which xqueue relies
  apt: pkg={{','.join(xqueue_debian_pkgs)}} state=present
  notify:
  - xqueue | restart xqueue

- include: deploy.yml tags=deploy




